address = "0.0.0.0"
port = 3000
log_level = "debug"

[qq]
app_id = 123
client_secret = "xxx"
interval = 1000

[features.ai]
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "xxx"
model = "qwen-plus"

[features.news]
url = "https://60s.yunnet.top"


[proxy]
enabled = false
kind = "http"
address = "xxx"
port = 1080
username = "xxx"
password = "xxx"