name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      # 拉仓库
      - name: Checkout
        uses: actions/checkout@v4

      # 登录 Docker Registry（yunnet 私有仓库）
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.yunnet.top
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build Docker Image
        run: |
          docker build -t harbor.yunnet.top/all/rbot:latest .
          docker tag harbor.yunnet.top/all/rbot:latest harbor.yunnet.top/all/rbot:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push harbor.yunnet.top/all/rbot:latest
          docker push harbor.yunnet.top/all/rbot:${{ github.sha }}